# Site settings
title: "木卯溪•天天向上"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mumaoxi.github.io" # the base hostname & protocol for your site
github_username: mumaoxi

timezone: Beijing
# Build settings
highlighter: pygments
permalink: /:categories/:title/

# markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - tables

paginate: 10

theme: clean-blog
copyright: 版权